apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-dev
  labels:
    app: webapp-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-dev
  template:
    metadata:
      labels:
        app: webapp-dev
    spec:
      containers:
      - name: web-container-dev
        image: 10.38.91.61/library-dev/harbor_cicd:v5
        ports:
        - containerPort: 80
