apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-dev
  labels:
    app: webapp-dev
spec:
  replicas: 10
  selector:
    matchLabels:
      app: webapp-dev
  template:
    metadata:
      labels:
        app: webapp-dev
    spec:
      containers:
      - name: web-container-dev
        image: 192.168.8.135:80/library-dev/harbor_cicd:v17
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service-dev
spec:
  selector:
    app: webapp-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
